### PR TITLE
A method to allow developer to inject HttpContext into WebService class.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by csharpfritz** [comment]
Thank you very much for the contribution Doug!

This looks really good...  can you help me out by writing a validating unit test in the WebFormsTest.Test project that exercises a service in the WebFormsTest.Web project.  This way, we can ensure that your method works through other modifications.

**Comment by ghost** [comment]
Yep, I can do that. I'll see if I can get to it sometime later this week.

**Comment by csharpfritz** [comment]
Very cool...  as you can see from the interval that I work on this, its not
something I can focus on right now.  I pick it up every few weeks and
finish a feature or two.

Jeff

**Comment by ghost** [comment]
Figured this was a side project for you but am very glad that I found it. It has been useful with several WebForms apps that the company I'm working for is still supporting and adding new features to and its making it easier to test those projects.

**Comment by ghost** [comment]
Hi Jeff,

I've added two unit tests for the inject context into web service. I kinda forgot about the pull request; got busy with other things. Anyway, I think the tests that I've added add a pretty good amount of coverage to that method.

See ya,

Doug

**Comment by csharpfritz** [comment]
This looks like a good test - simple and ensures the bare minimum works

**Comment by csharpfritz** [comment]
I'll follow up later with an entry on the Wiki about how to inject into a Service

**Comment by ghost** [comment]
Awesome!

**Pull request merged**
